language: java

os: linux
dist: trusty
jdk: oraclejdk8

jobs:
  include:
    - stage: "Build project"
      script:
      - ./gradlew build

deploy:
  provider: heroku
  app: lf-cities-api
  api_key: $HEROKU_KEY